### ISSUE TITLE
Convert codetag scopes to lowercase

### ISSUE THREAD

**Issue by howlinweed** [howlinweed/language-crusader-kings--i-i#12]
Change `2: name: 'entity.name.codetag.$2'` to `2: name: 'entity.name.codetag.${2:/downcase}'` to get the scope names in lowercase.

**Comment by WottatoParrior** [comment]
Hi i would like to help, but i am having a bit of trouble.

I am trying to locate the issue but i cant seem to find it?

Its inside the spec folder right?

**Comment by howlinweed** [comment]
Oh hey, thanks! It is line [735 of  grammars/language-ck2.cson](https://github.com/howlinweed/language-crusader-kings--i-i/blob/master/grammars/language-ck2.cson#L735). Feel free to poke around the code.

**Comment by WottatoParrior** [comment]
Ok so what i am thinking is doing `2: name: 'entity.name.codetag.${2:/downcase}'` or `2: name: 'entity.name.codetag.$2'.toLowerCase()`.

Am i thinking this correctly?

**Comment by howlinweed** [comment]
Yes, go ahead and use the `2: name: 'entity.name.codetag.${2:/downcase}'` code since I've already started using that syntax for other matches.

**Comment by WottatoParrior** [comment]
The other one doesn't work?
Asking out of curiosity

**Comment by howlinweed** [comment]
No, it doesn't appear to work. The downcase command is provided by [first-mate](https://github.com/atom/first-mate) which [calls `toLowerCase` under the hood](https://github.com/atom/first-mate/blob/9295b5632a2eb5d0716da736aba08ce3f4e3237e/src/pattern.coffee#L128).

**Comment by howlinweed** [comment]
You're changes have been merged in. Thanks for all the help, and I'll make sure to add your username to the contributors statement.
